<?php

$pornstars = [
  "Karlee Grey",
  "Aryana Adin",
  "Mia Marin",
  "Ana Rose",
  "Lana Rhoades",
  "Riley Reid",
  "Abella Danger",
  "Eva Elfie",
  "Mia Malkova",
  "Brandi Love",
  "Mia Khalifa",
  "Cory Chase",
  "Nicole Aniston",
  "Autumn Falls",
  "Angela White",
  "Lena Paul",
  "Adriana Chechik",
  "Alex Adams",
  "Jordi El Nino Polla",
  "Emily Willis",
  "Ava Addams",
  "Lela Star",
  "Leolulu",
  "Danika Mori",
  "Elsa Jean",
  "Alexis Texas",
  "Kendra Lust",
  "Lisa Ann",
  "Skylar Vox",
  "Gabbie Carter",
  "Rae Lil Black",
  "MyKinkyDope",
  "Dani Daniels",
  "Sara Jay",
  "Xev Bellringer",
  "Johnny Sins",
  "Jessa Rhodes",
  "Dillion Harper",
  "Asa Akira",
  "Kimmy Granger",
  "Alexis Fawx",
  "Sarah Banks",
  "Valentina Nappi",
  "Britney Amber",
  "Gina Valentina",
  "Karlee Grey",
  "Lexi Lore",
  "Alina Lopez",
  "Leah Gotti",
  "Indigo White",
  "LaSirena69",
  "Janice Griffith",
  "Madison Ivy",
  "Kim Kardashian",
  "Lexi Luna",
  "Eva Lovia",
  "Cherie DeVille",
  "Peta Jensen",
  "Kelsi Monroe",
  "Sophie Dee",
  "Piper Perri",
  "Kenzie Madison",
  "Kenzie Reeves",
  "Megan Rain",
  "Rose Monroe Your Fav",
  "Sasha Grey",
  "Owen Gray",
  "Kendra Sunderland",
  "Bridgette B",
  "Mandy Muse",
  "Little Caprice",
  "Natasha Nice",
  "Nicolette Shea",
  "Luna Star",
  "Mandy Flores",
  "Karma Rx",
  "Vina Sky",
  "Melody Marks",
  "August Ames",
  "Athena Faris",
  "MySweetApple",
  "Kira Noir",
  "Krissy Lynn",
  "Moriah Mills",
  "Lady Fyre",
  "Mia Melano Official",
  "Blair Williams",
  "Rachel Starr",
  "Eliza Ibarra",
  "James Deen",
  "Madeincanarias",
  "Stella Cox",
  "Canela Skin",
  "Tori Black",
  "Lena The Plug",
  "Savannah Sixx",
  "Romi Rain",
  "Brooklyn Chase",
  "Honey Gold",
  "Veronica Rodriguez",
  "Julia Ann",
  "Gabriela Lopez",
  "Ashley Alban",
  "Kyle Balls WCA",
  "Lauren Phillips",
  "Sunny Leone",
  "Victoria June",
  "Blake Blossom",
  "Aletta Ocean",
  "Gianna Michaels",
  "Brianna Beach",
  "Anastasia Knight",
  "Phoenix Marie",
  "Codi Vore",
  "Ariella Ferrera",
  "Payton Preslee",
  "Kyler Quinn",
  "Sasha Rose",
  "Ricky Johnson",
  "Alison Tyler",
  "Desiree Dulce",
  "Jia Lissa",
  "Christy Mack",
  "Mark Rockwell",
  "Indica Flower",
  "Esperanza Gomez",
  "Nikki Brooks",
  "Violet Myers",
  "Liya Silver",
  "Anissa Kate",
  "Molly Jane",
  "Diamond Jackson",
  "Lacy Lennon",
  "Coco Vandi",
  "AJ Applegate",
  "Lucy Cat",
  "Jada Stevens",
  "Teanna Trump",
  "Savannah Bond",
  "Gia Paige",
  "Valerie Kay",
  "Aidra Fox",
  "Bailey Brooke",
  "Richelle Ryan",
  "Remy Lacroix",
  "Jayden James",
  "Marsha May",
  "JUNE LIU",
  "Jade Jordan",
  "Hitomi Tanaka",
  "Giselle Montes",
  "Lindsey Love",
  "Kagney Linn Karter",
  "Chanel Preston",
  "Sasha Foxxx",
  "Lil D",
  "Alex Grey",
  "Siri",
  "Emanuelly Raquel",
  "Haley Reed",
  "Violet Starr",
  "Harley Dean",
  "Anna Bell Peaks",
  "Adria Rae",
  "Lulu Chu",
  "Ariana Marie",
  "Daisy Stone",
  "Miss Banana",
  "Audrey Bitoni",
  "Eva Notty",
  "Gina Gerson",
  "Danny D",
  "Manuel Ferrara",
  "Krystal Boyd",
  "Kendra Spade",
  "Jasmine Jae",
  "Valentina Jewels",
  "Jewelz Blu",
  "Nikki Benz",
  "Kawaii Girl",
  "Aaliyah Hadid",
  "Naomi Woods",
  "Alexis Crystal",
  "Abigail Mac",
  "Maya Bijou",
  "Ella Hughes",
  "Elena Koshka",
  "Ryan Conner",
  "Katrina Jade",
  "Layla London",
  "Antonio Mallorca",
  "Bonnie Rotten",
  "Anya Olsen",
  "Katana Kombat",
  "Emma Hix",
  "Victoria Cakes",
  "Veronica Avluv",
  "Maru Karv",
  "Holly Michaels",
  "Jynx Maze",
  "Gianna Dior",
  "Nina Hartley",
  "Alura TNT Jenson",
  "Aria Lee",
  "Hazel Moore",
  "Angel Emily",
  "Kylie Page",
  "Anri Okita",
  "Reagan Foxx",
  "Jasmine Grey",
  "Bailey Base",
  "Kissa Sins",
  "Kristen Scott",
  "Stacy Cruz",
  "Rocco Siffredi",
  "India Summer",
  "Lexi Belle",
  "Ivy Lebelle",
  "Julie Cash",
  "Sybil",
  "Gia Derza",
  "Faye Reagan",
  "Alix Lynx",
  "Yua Mikami",
  "Bryci",
  "Larkin Love",
  "Clover Baltimore",
  "Apolonia Lapiedra",
  "Ai Uehara",
  "Cherry Crush",
  "Abella Anderson",
  "Jane Wilde",
  "Meana Wolf",
  "Ginebra Bellucci",
  "Juan El Caballo Loco",
  "Jade Kush",
  "Mila Azul",
  "Vanna Bardot",
  "Sheena Ryder",
  "Alexa Grace",
  "Kayla Kayden",
  "Jodi West",
  "Keisha Grey",
  "Alex Blake",
  "Cecilia Lion",
  "Nia Nacci",
  "Adriana Maya",
  "Nacho Vidal",
  "Natalia Starr",
  "Amia Miley",
  "Sharon Lee",
  "Daisy Taylor",
  "Carolina Sweets",
  "Tiffany Watson",
  "Ella Knox",
  "King Nasir",
  "Sydney Cole",
  "Osa Lovely",
  "Cassidy Banks",
  "Angel Wicky",
  "Charity Crawford",
  "Dakota Skye",
  "Maitland Ward",
  "Tiffany Tatum",
  "Cherokee D Ass",
  "Vanessa Cage",
  "Katie Kush",
  "Mandingo",
  "Melanie Hicks",
  "Ryan Ryans",
  "Michael Masters",
  "Lucie Wilde",
  "Jada Kai",
  "Nina Elle",
  "Abigaile Johnson",
  "Dolly Little",
  "Franceska Jaimes",
  "Brittney White",
  "Veronica Leal",
  "Demi Sutra",
  "Katie Cummings",
  "Stormy Daniels",
  "Uma Jolie",
  "Kirara Asuka",
  "Kayden Kross",
  "Amber Alena",
  "Yhivi",
  "Kiara Cole",
  "Jill Kassidy",
  "Susi Gala",
  "Scarlit Scandal",
  "Penny Pax",
  "Katie Morgan",
  "Noelle Easton",
  "Alena Croft",
  "Sarah Vandella",
  "Naomi Swann",
  "Amanda Lane",
  "Ryan Keely",
  "Keiran Lee",
  "Bunny Colby",
  "Princess Leia",
  "Karla Kush",
  "Summer Hart",
  "Ava Devine",
  "Mistress T",
  "Abby Cross",
  "Tessa Taylor",
  "Jennifer White",
  "Sofia Lee",
  "Lily Adams",
  "Josephine Jackson",
  "Heather Vahn",
  "Alex Coal",
  "Aryana Adin",
  "Skye Blue",
  "Monique Alexander",
  "Crystal Rush",
  "Syren De Mer",
  "Queen Rogue",
  "August Taylor",
  "Ms London",
  "Aria Alexander",
  "Havana Bleu",
  "Bruce Venture",
  "Cadey Mercury",
  "Jenna Jameson",
  "Zoey Holloway",
  "Naomi Russell",
  "Mary Moody",
  "Pinky",
  "Samantha Saint",
  "Amirah Adara",
  "Aubrey Sinclair",
  "Lily Larimar",
  "Lucy Li",
  "Katrina Moreno",
  "Holly Hendrix",
  "Hannah Hays",
  "Skyla Novea",
  "Sophia Leone",
  "Cali Carter",
  "Kenna James",
  "Ava Taylor",
  "Julianna Vega",
  "Janet Mason",
  "Whitney Wright",
  "Serena Santos",
  "Ashley Fires",
  "Stoya",
  "Ashley Adams",
  "Cassidy Klein",
  "Olivia Austin",
  "Yui Hatano",
  "Helena Price",
  "Kali Roses",
  "Lily Jordan",
  "Xander Corvus",
  "Harmony Wonder",
  "Brooke Beretta",
  "Nancy A",
  "Priya Rai",
  "Dani Jensen",
  "Carter Cruise",
  "Heather Harmon",
  "Rebeca Linares",
  "Kiara Mia",
  "Kianna Dior",
  "Ashly Anderson",
  "Brenna Sparks",
  "Becky Bandini",
  "Jasmine James",
  "Molly Stewart",
  "Lily Rader",
  "Anya Ivy",
  "Arabelle Raphael",
  "Jenna Haze",
  "Foxy Di",
  "Lara Cumkitten",
  "Connie Carter",
  "Elisa Sanches",
  "Silvia Saige",
  "Evelin Stone",
  "Blondie Fesser",
  "Amanda Cerny",
  "Tera Patrick",
  "Malena Morgan",
  "Saya Karim",
  "Cameron Canela",
  "Jessica Robbin",
  "Alina Li",
  "Amy Anderssen",
  "Chris Diamond",
  "Maserati",
  "Maria Ozawa",
  "Shyla Stylez",
  "Pamela Rios",
  "Paige Owens",
  "Jillian Janson",
  "Kiki Minaj",
  "Reena Sky",
  "Angelina Castro",
  "Darcie Dolce",
  "Charlotte Sartre",
  "Vanessa Veracruz",
  "Katie Banks",
  "Ana Foxxx",
  "Winter Jade",
  "Sensual Jane",
  "Tru Kait",
  "Ana Rose",
  "Aubrey Black",
  "Hoby Buchanon",
  "Sofia Rose",
  "Izzy Bell",
  "April O'Neil",
  "Lou Nesbit",
  "Anna Polina",
  "Jenny Blighe",
  "Brooklyn Gray",
  "Lex Steele",
  "Emily Addison",
  "Harmony Reigns",
  "Azul Hermosa",
  "Mia Marin",
  "Lola Fae",
  "Alina Belle",
  "Melissa Moore",
  "Natalie Mars",
  "Amber Hahn",
  "Laz Fyre",
  "Alexa Tomas",
  "Bella Rolland",
  "Amarna Miller",
  "Alessa Savage",
  "Zoe Doll",
  "MJ Fresh",
  "Katerina Hartlova",
  "Athena Palomino",
  "Azumi Mizushima",
  "Emily Lynne",
  "Kate Truu",
  "Nekane",
  "Jada Fire",
  "Eva Angelina",
  "TINY TEXIE",
  "Chloe Temple",
  "Brandi Bae",
  "Diamond Kitty",
  "Tyler Nixon",
  "Clea Gaultier",
  "Cock Ninja",
  "Liza Del Sierra",
  "Nathaly Cherie",
  "Arietta Adams",
  "Pamela Anderson",
  "Marry Queen",
  "Aimi Yoshikawa",
  "Tia Cyrus",
  "Avery Cristy",
  "Rebecca More",
  "Shae Summers",
  "Nina North",
  "Nikita Bellucci",
  "Katya Clover",
  "Chanell Heart",
  "Dava Foxx",
  "Bree Olson",
  "Kimber Lee",
  "Skin Diamond",
  "Kleio Valentien",
  "Ashlynn Brooke",
  "Jessie Rogers",
  "Liza Rowe",
  "Madame Amiee Cambridge",
  "Stacey Saran",
  "Bella Brookz",
  "Tory Lane",
  "Arya Fae",
  "Pristine Edge",
  "Misty Stone",
  "Natalie Knight",
  "Miss Raquel",
  "Mia Bandini",
  "Marley Brinx",
  "Jaye Summers",
  "Mike Adriano",
  "Charlee Chase",
  "Christie Stevens",
  "Casey Calvert",
  "Tiffany Leiddi",
  "Cytheria",
  "Aria Sky",
  "Kylie Quinn",
  "Blaire Ivory",
  "Megan Sage",
  "Kendall Woods",
  "Aria Banks",
  "Nina Kayy",
  "Virgo Peridot",
  "Chloe Amour",
  "Alanah Rae",
  "Kelly Divine",
  "Ginger Banks",
  "Joseline Kelly",
  "Riley Jean",
  "Addie Andrews",
  "Chloe Cherry",
  "Hannah Brooks",
  "Skylar Valentine",
  "Tina Kay",
  "Carmella Bing",
  "ImMeganLive",
  "Katsuni",
  "Evelyn Claire",
  "Marina Visconti"
];

$servername = "localhost";
$username = "gif";
$password = "Scbwd2blah123";
$database = "porngifs";

$conn = mysqli_connect($servername, $username, $password, $database);

if($conn === false){
    die("ERROR: Could not connect. " . mysqli_connect_error());
}

$s_1 = ["pornstar","porn star","porno star","porno actress","porn actress","whore","fuck star","sex actress"];
$s_2 = ["amazing","hot","the best","young","veteran","top","easiest","top rated","cheapest","famous","recent"];
$s_3 = ["BBW","Asian","Blonde","Burnette","Red Head","Ebony","Teen","Amateur"];
$s_4 = ["great","good","top rated","the best","amazing","experienced","a professional"];
$s_5 = ["anal","butt","titty","pussy","blowjob","doggystlye","threesome","gangbang","69","missionary"];


$w1 = array_rand($s_1);
$w2 = array_rand($s_2);
$w3 = array_rand($s_3);
$w4 = array_rand($s_4);
$w5 = array_rand($s_5);


foreach($pornstars as $pornstar){

	$w1 = array_rand($s_1);
	$w2 = array_rand($s_2);
	$w3 = array_rand($s_3);
	$w4 = array_rand($s_4);
	$w5 = array_rand($s_5);

	$description = "This ".$s_1[$w1]." is a ".$s_2[$w2]." ".$s_3[$w3]." that is ".$s_4[$w4]." at ".$s_5[$w5]." fucking.";

	$sql = "INSERT INTO pornstars (pornstar, description) VALUES ('".$pornstar."','".$description."')";

	if(mysqli_query($conn, $sql)){
	    echo "Records inserted successfully.";
	} else{
	    echo "ERROR: Could not able to execute $sql. " . mysqli_error($conn);
	}

}



$conn->close();

?>